# Generated by Django 5.1.1 on 2024-09-09 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_rename_projects_project'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='crreated_at',
            new_name='created_at',
        ),
    ]
